# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93116fbcf2832308f57725a0a69bf5c46094f94f47272a14a628e6067fc6dbabb38ff9de1d11a177b1720d348cfc11a8b03ee76de426f459a66ed50259d70fbc

test:
  secret_key_base: b7d352809a7c281bb0519831ff9e60056178f367e9da7b11847a209398f394e6f268a901ad79b8a7c4d7aafa4f99e3ecfa3cb6f04e6416b55575f5ab23ae77af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
